apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-tonamel-test
  labels:
    app: flask-tonamel-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-tonamel-scraper
  template:
    metadata:
      labels:
        app: flask-tonamel-scraper
    spec:
      containers:
      - name: flask-scraper
        image: black0803/flask-tonamel-scraper:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-tonamel-service
spec:
  selector:
    app: flask-tonamel-scraper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer