version: "3.9"

services:
  sqs-elasticmq:
    image: docker.io/softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - my-network
    restart: unless-stopped

  flask-tonamel-scraper-server:
    image: black0803/flask-tonamel-scraper-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - sqs-elasticmq
      - scylla
    environment:
      - AWS_ACCESS_KEY_ID=None
      - AWS_SECRET_ACCESS_KEY=None
      - AWS_REGION=None
      - SQS_ENDPOINT=http://sqs-elasticmq:9324
      - DYNAMODB_ENDPOINT=http://scylla:8000
      - SQS_USE_SSL=False
      - USE_SCYLLA=True
    networks:
      - my-network
    restart: unless-stopped

  tonamel-scraper:
    image: black0803/tonamel-scraper:latest
    depends_on:
      - sqs-elasticmq
      - scylla
    environment:
      - AWS_ACCESS_KEY_ID=None
      - AWS_SECRET_ACCESS_KEY=None
      - AWS_REGION=None
      - SQS_ENDPOINT=http://sqs-elasticmq:9324
      - DYNAMODB_ENDPOINT=http://scylla:8000
      - SQS_USE_SSL=False
      - USE_SCYLLA=True
    networks:
      - my-network
    restart: unless-stopped

  scylla:
    image: scylladb/scylla:latest
    ports:
      - "9042:9042" # CQL port
      - "7000:7000" # Intra-node communication
      - "7001:7001" # Intra-node communication
      - "9160:9160" # Thrift
      - "8000:8000" # DynamoDB-compatible API port
    volumes:
      - scylla-data:/var/lib/scylla
    command:
      - "--alternator-port=8000"
      - "--alternator-write-isolation=always"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:

volumes:
  scylla-data: