name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Download and extract external zip
    #   run: |
    #     wget -O external.zip "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.126/linux64/chromedriver-linux64.zip"
    #     mkdir -p external_data
    #     unzip external.zip -d external_data  # Extracts to a directory named 'external_data'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub (optional)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/flask-tonamel-scraper:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/flask-tonamel-scraper:${{ github.sha }}
        # build-args: |
        #   CHROMEDRIVER_PATH=external_data/
